package clase_8_calculadora;

import javax.swing.JOptionPane;

/**
 *
 * @author ervargas
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lresultado = new javax.swing.JLabel();
        lvalor1 = new javax.swing.JLabel();
        lvalor2 = new javax.swing.JLabel();
        bcalcular = new javax.swing.JButton();
        tvalor1 = new javax.swing.JTextField();
        tvalor2 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        rbsuma = new javax.swing.JRadioButton();
        rbresta = new javax.swing.JRadioButton();
        rbmultiplica = new javax.swing.JRadioButton();
        rbdivicion = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setPreferredSize(new java.awt.Dimension(620, 400));
        setSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(null);

        lresultado.setBackground(new java.awt.Color(0, 0, 0));
        lresultado.setFont(new java.awt.Font("Calculator", 1, 30)); // NOI18N
        lresultado.setForeground(new java.awt.Color(0, 153, 0));
        lresultado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(lresultado);
        lresultado.setBounds(40, 20, 530, 56);
        lresultado.getAccessibleContext().setAccessibleName("lresultado");

        lvalor1.setText("Valor 1");
        getContentPane().add(lvalor1);
        lvalor1.setBounds(90, 110, 50, 16);
        lvalor1.getAccessibleContext().setAccessibleName("lvarlor1");

        lvalor2.setText("Valor 2");
        getContentPane().add(lvalor2);
        lvalor2.setBounds(490, 110, 50, 16);
        lvalor2.getAccessibleContext().setAccessibleName("lvalor2");

        bcalcular.setText("CALCULAR");
        bcalcular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bcalcularMouseEntered(evt);
            }
        });
        bcalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcalcularActionPerformed(evt);
            }
        });
        getContentPane().add(bcalcular);
        bcalcular.setBounds(200, 260, 210, 50);

        tvalor1.setFont(new java.awt.Font("Fira Code", 1, 36)); // NOI18N
        tvalor1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(tvalor1);
        tvalor1.setBounds(40, 140, 130, 80);

        tvalor2.setFont(new java.awt.Font("Fira Code", 1, 36)); // NOI18N
        tvalor2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tvalor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tvalor2ActionPerformed(evt);
            }
        });
        getContentPane().add(tvalor2);
        tvalor2.setBounds(440, 140, 130, 80);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        buttonGroup1.add(rbsuma);
        rbsuma.setText("SUMA");
        jPanel1.add(rbsuma);

        buttonGroup1.add(rbresta);
        rbresta.setText("RESTA");
        rbresta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbrestaActionPerformed(evt);
            }
        });
        jPanel1.add(rbresta);

        buttonGroup1.add(rbmultiplica);
        rbmultiplica.setText("MULTIPLICA");
        jPanel1.add(rbmultiplica);

        buttonGroup1.add(rbdivicion);
        rbdivicion.setText("DIVICION");
        rbdivicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbdivicionActionPerformed(evt);
            }
        });
        jPanel1.add(rbdivicion);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(200, 140, 220, 80);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jPanel2);
        jPanel2.setBounds(30, 10, 550, 80);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbdivicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbdivicionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbdivicionActionPerformed

    private void bcalcularMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_bcalcularMouseEntered
        // TODO add your handling code here:
    }// GEN-LAST:event_bcalcularMouseEntered

    private void rbrestaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_rbrestaActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_rbrestaActionPerformed

    private void bcalcularActionPerformed(java.awt.event.ActionEvent evt) {
        // Verificar que los campos de texto contengan datos
        if (tvalor1.getText().length() == 0 || tvalor2.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Por favor ingrese los dos valores.");
            return;
        }

        // Convertir de string a float
        float valor1 = Float.parseFloat(tvalor1.getText());
        float valor2 = Float.parseFloat(tvalor2.getText());

        float resultado = 0;
        if (rbsuma.isSelected()) {
            resultado = valor1 + valor2;
        } else if (rbresta.isSelected()) {
            resultado = valor1 - valor2;
        } else if (rbmultiplica.isSelected()) {
            resultado = valor1 * valor2;
        } else if (rbdivicion.isSelected()) {
            resultado = valor1 / valor2;
        } else {
            lresultado.setText("No se ha seleccionado ninguna operacion");
            return;
        }

        // Formatear la salida del resultado con dos decimales
        if (resultado % 1 == 0) {
            // El resultado es un número entero, mostrarlo sin decimales
            lresultado.setText(String.format("%d", (int) resultado));
        } else {
            // El resultado tiene decimales, mostrarlo con dos decimales
            lresultado.setText(String.format("%.2f", resultado));
        }
    }// GEN-LAST:event_bcalcularActionPerformed

    private void tvalor2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tvalor2ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_tvalor2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bcalcular;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lresultado;
    private javax.swing.JLabel lvalor1;
    private javax.swing.JLabel lvalor2;
    private javax.swing.JRadioButton rbdivicion;
    private javax.swing.JRadioButton rbmultiplica;
    private javax.swing.JRadioButton rbresta;
    private javax.swing.JRadioButton rbsuma;
    private javax.swing.JTextField tvalor1;
    private javax.swing.JTextField tvalor2;
    // End of variables declaration//GEN-END:variables
}
